using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tiket_Garuda
{
    class Biodata
    {
        public static void biodata()
        {
        
        System.Console.OutputEncoding = System.Text.Encoding.UTF8;
            System.Console.Write("\u00a9"); Console.Write("2018 SKYNET IT Solution. All rights reserved.");
            Console.WriteLine("\nPROGRAM INI SEMATA-MATA HASIL USAHA KAMI DAN MEMILIKI HAK CIPTA\n");
            Console.WriteLine("Kelompok 42");
            Console.WriteLine("Nama : Tedy Anggi Firdaus\t\tNama : Faiz Noerdiyan Chesara");
            Console.WriteLine("NIM  : 211201130055      \t\tNIM  : 211201130060");
            Console.ReadLine();
            Console.Clear();
        }
    }
}
